# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '13 13 * * *' # really?  No @daily?

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make image
    - name: test
      run: docker run --rm ruby_language_server rake | tee test.log
    - name: rubocop
      run: docker run --rm ruby_language_server rubocop | tee rubocop.log
